SELECT PRODUCT,BLAZE_ACTION_TYPE_DESC,BLAZE_TAG_NAME_DESC, sum(VWR_INTERACTION) as Vwrclickintraction, 
sum(ENG_INTERACTION) as Engclickintraction, sum(DPE_INTERACTION) as Dpeclickintraction 
FROM TFR_REP.EOC_INTERACTION_DETAIL_VIEW WHERE IO_ID = {0} AND TO_CHAR(TO_DATE(DAY_DESC, 'MM/DD/YYYY'),'YYYY-MM-DD') BETWEEN '{1}' AND '{2}' 
AND BLAZE_ACTION_TYPE_DESC = 'Click-thru' GROUP BY PRODUCT,BLAZE_ACTION_TYPE_DESC,BLAZE_TAG_NAME_DESC ORDER BY PRODUCT