SELECT substr(PLACEMENT_DESC,1,INSTR(PLACEMENT_DESC, '.', 1)-1) as Placement#,sum(VWR_MUTE) as Vwrmute,
sum(VWR_UNMUTE) as Vwrunmute,sum(VWR_PAUSE) as Vwrpause,
sum(VWR_REWIND) as Vwrrewind, sum(VWR_RESUME) as Vwrresume,sum(VWR_REPLAY) as Vwrreplay, 
sum(VWR_FULL_SCREEN) as Vwrfullscreen FROM TFR_REP.EOC_VIDEO_DETAIL_VIEW WHERE IO_ID = {0} AND TO_CHAR(TO_DATE(DAY_DESC, 'MM/DD/YYYY'),'YYYY-MM-DD') BETWEEN '{1}' AND '{2}'
GROUP BY PLACEMENT_ID, PLACEMENT_DESC ORDER BY PLACEMENT_ID