select substr(PLACEMENT_DESC,1,INSTR(PLACEMENT_DESC, '.', 1)-1) as PLACEMENT#,PRODUCT,
sum(IMPRESSIONS) as Impressions, sum(ENGAGEMENTS) as Engagements, 
sum(DPE_ENGAGEMENTS) as DpeEngagements, sum(CPCV_COUNT) as Completions,
sum(ENG_CLICK_THROUGHS) as EngClickthrough, 
sum(DPE_CLICK_THROUGHS) as DpeClickthrough,sum(VWR_CLICK_THROUGHS) as VwrClickthrough, 
sum(ENG_TOTAL_TIME_SPENT) as Engtotaltimespent,sum(DPE_TOTAL_TIME_SPENT) as Dpetotaltimespent, 
sum(VWR_VIDEO_VIEW_0_PC_COUNT) as View0,sum(VWR_VIDEO_VIEW_25_PC_COUNT) as View25,
sum(VWR_VIDEO_VIEW_50_PC_COUNT) as View50,sum(VWR_VIDEO_VIEW_75_PC_COUNT) as View75,
sum(VWR_VIDEO_VIEW_100_PC_COUNT) as View100,sum(ENG_VIDEO_VIEW_0_PC_COUNT) as Eng0,
sum(ENG_VIDEO_VIEW_25_PC_COUNT) as Eng25,sum(ENG_VIDEO_VIEW_50_PC_COUNT) as Eng50,
sum(ENG_VIDEO_VIEW_75_PC_COUNT) as Eng75,sum(ENG_VIDEO_VIEW_100_PC_COUNT) as Eng100,
sum(DPE_VIDEO_VIEW_0_PC_COUNT) as Dpe0,sum(DPE_VIDEO_VIEW_25_PC_COUNT) as Dpe25,
sum(DPE_VIDEO_VIEW_50_PC_COUNT) as Dpe50,sum(DPE_VIDEO_VIEW_75_PC_COUNT) as Dpe75,
sum(DPE_VIDEO_VIEW_100_PC_COUNT) as Dpe100,sum(DPE_INTERACTIVE_ENGAGEMENTS) as DpeIntractiveEngagements,
sum(ENG_INTERACTIVE_ENGAGEMENTS) as EngIntractiveEngagements
from TFR_REP.EOC_KEY_METRIC_VIEW 
WHERE IO_ID = {0} AND TO_CHAR(TO_DATE(DAY_DESC, 'MM/DD/YYYY'),'YYYY-MM-DD') BETWEEN '{1}' AND '{2}' 
GROUP BY PLACEMENT_ID, PLACEMENT_DESC, PRODUCT ORDER BY PLACEMENT_ID