select substr(PLACEMENT_DESC,1,INSTR(PLACEMENT_DESC, '.', 1)-1) as Placement#,BLAZE_TAG_NAME_DESC as Click_Tag, 
sum(VWR_INTERACTION) as VWR_Clickthrough from TFR_REP.EOC_INTERACTION_DETAIL_VIEW WHERE IO_ID = {0} and BLAZE_ACTION_TYPE_DESC = 'Click-thru' 
AND TO_CHAR(TO_DATE(DAY_DESC, 'MM/DD/YYYY'),'YYYY-MM-DD') BETWEEN '{1}' AND '{2}'
GROUP BY PLACEMENT_ID, PLACEMENT_DESC, BLAZE_TAG_NAME_DESC ORDER BY PLACEMENT_ID