select substr(PLACEMENT_DESC,1,INSTR(PLACEMENT_DESC, '.', 1)-1) as Placement#, 
sum(IMPRESSIONS) as Impression, sum(CPCV_COUNT) as Completions,sum(VWR_CLICK_THROUGHS) as Clickthroughs , 
sum(VWR_VIDEO_VIEW_100_PC_COUNT) as Video_Completions from TFR_REP.EOC_KEY_METRIC_VIEW 
WHERE IO_ID = {0} AND TO_CHAR(TO_DATE(DAY_DESC, 'MM/DD/YYYY'),'YYYY-MM-DD') BETWEEN '{1}' AND '{2}'
GROUP BY PLACEMENT_ID, PLACEMENT_DESC ORDER BY PLACEMENT_ID