select substr(PLACEMENT_DESC,1,INSTR(PLACEMENT_DESC, '.', 1)-1) as Placement#, 
sum(IMPRESSIONS) as Impression, sum(ENGAGEMENTS) as Eng, 
sum(DPE_ENGAGEMENTS) as Deep,sum(CPCV_COUNT) as Completions from TFR_REP.EOC_KEY_METRIC_VIEW 
WHERE IO_ID = {0} AND TO_CHAR(TO_DATE(DAY_DESC, 'MM/DD/YYYY'),'YYYY-MM-DD') BETWEEN '{1}' AND '{2}' 
GROUP BY PLACEMENT_ID, PLACEMENT_DESC ORDER BY PLACEMENT_ID