select substr(PLACEMENT_DESC,1,INSTR(PLACEMENT_DESC, '.', 1)-1) as Placement#,
FEV_INT_VIDEO_DESC,sum(VWR_VIDEO_VIEW_0_PC_COUNT) as Views0,
sum(VWR_VIDEO_VIEW_25_PC_COUNT) as Views25,sum(VWR_VIDEO_VIEW_50_PC_COUNT) as Views50,
sum(VWR_VIDEO_VIEW_75_PC_COUNT) as Views75,sum(VWR_VIDEO_VIEW_100_PC_COUNT) as Video_Completions FROM TFR_REP.EOC_VIDEO_DETAIL_VIEW 
WHERE IO_ID = {0} AND TO_CHAR(TO_DATE(DAY_DESC, 'MM/DD/YYYY'),'YYYY-MM-DD') BETWEEN '{1}' AND '{2}'
GROUP BY PLACEMENT_ID, 
PLACEMENT_DESC,FEV_INT_VIDEO_DESC ORDER BY PLACEMENT_ID