select substr(PLACEMENT_DESC,1,INSTR(PLACEMENT_DESC, '.', 1)-1) as Placement#,PRODUCT,sum(IMPRESSIONS) as Impressions,sum(ENGAGEMENTS) as Engagements, 
sum(CPCV_COUNT) as completions,sum(DPE_ENGAGEMENTS) as Dpeengagements
From TFR_REP.EOC_KEY_METRIC_VIEW WHERE IO_ID = {0} AND TO_CHAR(TO_DATE(DAY_DESC, 'MM/DD/YYYY'),'YYYY-MM-DD') BETWEEN '{1}' AND '{2}' GROUP BY PLACEMENT_ID,
PLACEMENT_DESC,PRODUCT ORDER BY  PLACEMENT_ID